plugins {
    id 'com.android.application' version '8.2.2'
}

android {
    namespace 'dev.sasnews.mediatoggle'
    compileSdk 34
    defaultConfig {
        applicationId "dev.sasnews.mediatoggle"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    signingConfigs {
        release {
            def keystorePath = System.getenv("KEYSTORE_PATH")
            if (keystorePath != null && !keystorePath.isEmpty() && new File(keystorePath).exists()) {
                storeFile file(keystorePath)
                storePassword System.getenv("KEYSTORE_PASSWORD")
                keyAlias System.getenv("KEY_ALIAS")
                keyPassword System.getenv("KEYSTORE_PASSWORD")
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            def keystorePath = System.getenv("KEYSTORE_PATH")
            if (keystorePath != null && !keystorePath.isEmpty() && new File(keystorePath).exists()) {
                signingConfig signingConfigs.release
            }
        }
        debug {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.12.0'
    testImplementation 'junit:junit:4.13.2'
}